
version: "3"
services:
  reverseproxy:
    build:
      context: ./
    image: lucasbrogni/reverse-proxy
  backend_user:
    build:
      context: ../../user-api
    image: lucasbrogni/user-udagram-lucasbrogni
  backend_feed:
    build:
      context: ../../feed-api
    image: lucasbrogni/feed-udagram-lucasbrogni
  frontend:
    build:
      context: ../../udagram-frontend
    image: lucasbrogni/fe-udagram-lucasbrogni
